# Starter pipeline
- task: ServiceFabricUpdateManifests@2
  inputs:
    updateType: 'Manifest versions'
    applicationPackagePath: 'The Alchemist''s Transformational Journey (real-life-video-game)'
    versionSuffix: '.(Build.BuildNumber)'
    updateOnlyChanged: false
- task: VisualStudioTestPlatformInstaller@1
- task: SpecFlowPlus@0
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: 'crystal.ai'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
